// action types
export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

// api call types
export const MAKE_API_REQUEST = 'MAKE_API_REQUEST';
export const MAKE_API_REQUEST_SUCCESS = 'MAKE_API_REQUEST_SUCCESS';
export const MAKE_API_REQUEST_FAILURE = 'MAKE_API_REQUEST_FAILURE';

//Toast types
export const DISPATCH_TOAST_SUCCESS = 'DISPATCH_TOAST_SUCCESS';
export const DISPATCH_TOAST_FAILURE = 'DISPATCH_TOAST_FAILURE';
export const DISPATCH_TOAST_INFO = 'DISPATCH_TOAST_INFO';
export const DISPATCH_TOAST_WARNING = 'DISPATCH_TOAST_WARNING';

// function action types
export const ADLAPP_IS_USER_LOGIN = 'ADLAPP_IS_USER_LOGIN';
export const ADLAPP_FB_AUTHANTICATE = 'ADLAPP_FB_AUTHANTICATE';
export const ADLAPP_GET_NEWS = 'ADLAPP_GET_NEWS';
export const ADLAPP_SET_PROFILE_DATA = 'ADLAPP_SET_PROFILE_DATA';
export const ADLAPP_GET_PROFILE_DATA = 'ADLAPP_GET_PROFILE_DATA';
export const ADLAPP_CLEAR_NEWS = 'ADLAPP_CLEAR_NEWS';
